# Generated by Django 4.0.6 on 2022-07-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoReactApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='BlogUser',
            new_name='blogUser',
        ),
    ]
